# Generated by Django 5.0.6 on 2024-07-03 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeboardPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_post_location', models.TextField(verbose_name='게시글 작성 위치')),
                ('free_post_title', models.TextField(verbose_name='게시글 제목')),
                ('free_post_content', models.TextField(verbose_name='게시글 내용')),
                ('free_post_created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('free_post_writer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
    ]
