# Generated by Django 5.0.6 on 2024-07-03 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeboardPostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_comment_content', models.TextField(verbose_name='댓글 내용')),
                ('free_comment_created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('free_comment_post_id', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, to='freeboard.freeboardpost')),
                ('free_comment_writer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
    ]
