# Generated by Django 5.0.6 on 2024-07-04 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_scrap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrap',
            old_name='scrap_id_scraped',
            new_name='scrap_is_scraped',
        ),
    ]
