# Generated by Django 5.0.6 on 2024-07-04 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_rename_scrap_id_scraped_scrap_scrap_is_scraped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrap',
            name='scrap_is_scraped',
        ),
    ]
