# Generated by Django 5.0.6 on 2024-07-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitboardPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruit_post_location', models.TextField(verbose_name='채용을 진행하는 곳의 위치')),
                ('recruit_post_title', models.TextField(verbose_name='게시글 제목')),
                ('recruit_post_content', models.TextField(verbose_name='게시글 내용')),
                ('free_post_created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('recruit_post_company', models.TextField(verbose_name='채용 진행 회사명')),
                ('recruit_post_img', models.ImageField(upload_to='', verbose_name='게시글 대표 이미지')),
            ],
        ),
    ]
